### ISSUE TITLE
A few tweaks

### ISSUE THREAD

**Issue by robinwhittleton** [weijia-cheng/taras-shevchenko_poetry#1]
content.opf:
- longdesc spelling mistakes: “Ukranian”, ”surveilance”, “emnity”

poetry:
- “Nor their fears dessembled” -> dissembled (checked against the source)

endnotes
- note 1-3 & 6: `<dfn>` rather than `<i>` / `<em>` (you’ll need to style these as italic too)
- note 8: Bible citation formatting should probably follow https://standardebooks.org/manual/1.6.4/single-page#8.17.4

**Comment by weijia-cheng** [comment]
Ok, done.

Interestingly `<dfn>` is styled as italics by default. I didn't have to add any CSS rules to get it to display as italics. Checked on both Firefox and my Kobo.
